name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      id: unit_tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Upload test results
      if: ${{ !cancelled() && hashFiles('reports/*-junit.xml') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/*-junit.xml
        if-no-files-found: error
    - name: Publish test results
      if: ${{ !cancelled() && (steps.unit_tests.outcome == 'success' || steps.unit_tests.outcome == 'failure') }}
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: reports/*-junit.xml
        check_name: Test results
        check_run: ${{ github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
        comment_mode: "off"
        compare_to_earlier_commit: false
        job_summary: true
        action_fail_on_inconclusive: true
