name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Report unit tests
      if: ${{ !cancelled() && hashFiles('reports/jest-junit.xml') != '' && github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
      uses: dorny/test-reporter@v1
      with:
        name: Unit test results
        path: reports/jest-junit.xml
        reporter: jest-junit
    - name: Report integration tests
      if: ${{ !cancelled() && hashFiles('reports/cypress-junit.xml') != '' && github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
      uses: dorny/test-reporter@v1
      with:
        name: Integration test results
        path: reports/cypress-junit.xml
        reporter: java-junit
